# Базовый образ
FROM golang:1.20-alpine as builder

RUN mkdir /api
ADD ./api/src /api/
WORKDIR /api

RUN apk update && apk add --no-cache git ca-certificates && \
    go mod init knocker && go mod tidy && CGO_ENABLED=0 go build -ldflags="-s -w" -o main .

# Конечный образ
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /api/main .

CMD ["./main"]